title: Carme Documentation
logo: UserDoc/Images/carme-round.png
description: Documentation for the Carme project
show_downloads: true
google_analytics: true
theme: jekyll-theme-minimal

plugins:
  - jekyll-sitemap
